### ISSUE TITLE
Release 0.2.1 "FizzBuzz"

### ISSUE THREAD

**Issue by indeyets** [FreeFeed/issues#8]
## Необходимо
- [x] баг про localStorage pepyatka/pepyatka-html#492
- [x] починить Subscriptions pepyatka/pepyatka-server#241
  - [ ] при выводе фильтровать пустые записи
  - [x] в `User.prototype.updateLastActivityAt` вместо `that.id` использовать id таймлайна
  - [x] Copy this script to ./bin/ and run it: https://gist.github.com/epicmonkey/37e10cff049b290d1d7c
## Хорошо бы
- [x] правильная надпись вместо Home в шапке pepyatka/pepyatka-html#238
- [x] перевод фрифида на английский везде включая галку включения беттерфида https://github.com/pepyatka/pepyatka-html/issues/482

**Comment by berkus** [comment]
Сползают в 0.2.2:
- [ ] пагинация в My Discussions pepyatka/pepyatka-server#233

## Хорошо бы
- [ ] перегрузка данных для страницы при клике по текущей ссылке (например клик по «шапке» должен перегрузить индекс) pepyatka/pepyatka-html#233
